#
# Travis CI config file
#

language: python

python:
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get -y install libhdf5-dev
  - pip install poetry
install:
  - poetry install

# command to run tests
script:
  - poetry run pytest

